### ISSUE TITLE
Custom named setup results in default setup

### ISSUE THREAD

**Issue by innerjoin** [jazz-community/jazz-plugin-maven-archetype#8]
Running the following command:
> .\setup.ps1 -group org.jazz-community.example -version 0.0.1-SNAPSHOT -serviceName HelloCommunityService

I would expect it to be named as defined. But instead, the default name `com.siemens.example` is being used

**Comment by SBI-** [comment]
This only happens when calling a powershell script from cmd instead of powershell. The script is called but all parameters are ignored.
