### ISSUE TITLE
Service usage examples

### ISSUE THREAD

**Issue by SBI-** [jazz-community/jazz-plugin-maven-archetype#9]
It would be nice to have some examples on how to consume the services / interact with the deployed service. Maybe as a console application or a small web site.

**Comment by SBI-** [comment]
With both the [Bulk Mover Service](https://github.com/jazz-community/rtc-workitem-bulk-mover-service) and [Secure Property Store](https://github.com/jazz-community/rtc-secure-user-property-store) being published on the community, I don't think we need separate usage examples anymore.

**Comment by innerjoin** [comment]
What about a short section in the Readme to point to the services mentiomed above?
